/* === State Management === */
const AppState = {
  authToken: localStorage.getItem("auth_token") || null,
  currentUser: JSON.parse(localStorage.getItem("current_user") || "null"),
  currentTaskId: null,
  currentCatalog: [],
  currentChapter: null,
  approved: false,
  selectedVersions: [],
  projectDirty: false,
  currentTitle: "未命名项目",
  currentOutline: "",
  currentGenre: "urban_fantasy",
  currentStyle: "web_novel",
  currentTargetChapters: 10,
  currentPlannedChapters: 0,
  currentWordsPerChapter: 2000,
  allProjects: [],
  readerFontSize: 14,
  templatesCache: [],
  currentBatchId: localStorage.getItem("current_batch_id") || null,
  taskMonitorTimer: null,
  storyEvolution: null,
  workspacePrefsReady: false,
};
